### ISSUE TITLE
Rev1.1 CAD Design of Generic IVC filter

### ISSUE THREAD

**Issue by kenaycock** [kenaycock/Generic-IVC-Filter#2]
Hi Karthik, 

I uploaded new CAD files for the generic IVC filter along with a DXF file for the laser cutting:
https://github.com/kenaycock/Generic-IVC-Filter/tree/master/CAD/Rev1.1
Could you take a look at the updated files and see if we need to make further changes before proceeding with manufacturing a prototype? 

I assumed the following values in the CAD model based on those given in the *Open Stent* manuscript:
* Laser kerf width ("w_kerf"): 0.025mm
* Material removed during surface finishing:
    * "m_width": 0.036mm (i.e., 0.018mm from each side of the struts)
    * "m_thickness": 0.059mm (from the *inside* surface of the tube to remove draw lines)

Are these values appropriate for 1) this size of tubing and 2) our chosen surface finishing? I believe we decided on electropolishing during our last meeting.

I think specifying an accurate kerf width is all that really matters right now, but we will eventually need to know the material removed during surface finishing so that we can perform accurate FEA simulations using the "finished" device geometry. 

Anyway, I look forward to your feedback! 

Thanks,
Kenny

**Comment by karthikSenthi** [comment]
Hi Kenny,

I reviewed the CAD files and it all looks good. For the material removal due to surface finishing, you can assume the total removal from the strut width to be 0.025mm (i.e 0.0125mm from each side). For the wall thickness, it is better to specify the value and tolerances after measuring dimensions from initial prototypes. For now, just the initial starting thickness of the tube in the drawing should suffice. 

Please update the laser kerf width accounting for this new removal and upload the relevant files. Also for the dxf file, it seems you uploaded the coding for a tool path which we don't need. Instead, if you could save the "Laser Toolpath DXF" sheet of the SolidWorks drawing you created in a separate dxf/dwg file that should be good.

Thanks,
Karthik

**Comment by kenaycock** [comment]
Hi Karthik,

Okay, sounds good. The "as-cut" configurations that I uploaded are based on
a total laser kerf of 0.025mm as you said (0.0125mm per side), so I think
we are set. I can update the "finished" configurations after we make a
prototype. But, I can add an "as-cut, expanded" drawing if
you need that.

Regarding the DXF file, did you open this on your workstation, or did you
preview the file on GitHub? Since the file is ASCII, GitHub shows you the
raw code as if it were a toolpath or something, but if you open the file in
a DXF viewer it should load normally. Let me know if there's something
wrong though and I can re-export the drawing.

EDIT: Here's a direct link to the DXF file that you can save out from your browser using "File->Save as...":
https://raw.githubusercontent.com/kenaycock/Generic-IVC-Filter/master/CAD/Rev1.1/FDA_CP_Generic_IVC_Filter_Rev1.1_Laser_template.DXF

Thanks,
Kenny

**Comment by karthikSenthi** [comment]
Hi Kenny,

Just to clarify, I meant "m_width" to be 0.025mm (i.e the material removal from strut width) and not kerf_width. So the kerf_width will be higher than 0.025mm if you adjust the as-cut dimension accordingly.

I am able to view the dxf file after saving it to the computer. If you could upload the revised files then we should be good to produce the prototypes.

-Karthik

**Comment by kenaycock** [comment]
Hi Karthik, 

Thanks for the clarification. I misunderstood your first message. I can update "m_width" to 0.025mm (currently 0.036mm) as you directed. A couple more questions to clear this up: 

1. Should the laser kerf width also be 0.025mm, as I previously specified?
2. Should the "as cut" configuration include the laser kerf only and be independent of "m_width"?

Regarding (2), I'm slightly confused. In the _Open Stent_ manuscript, the "as cut" width is defined as:

> w_strut_raw = (D_tube * pi / N_struts) - w_kerf (Eqn. 3.38)

where:
> "w_kerf is the effective kerf width between struts when fabricated (or in the crimped state). In the typical case of laser micromachining of stent from tubing, this is the effective width of the laser beam:
w_kerf = 0.025mm   (Eqn. 3.11)"

The "as cut" configurations that I provided in the drawings thus far follow the procedure in the _Open Stent_ manuscript and account for the laser kerf only. But, it sounds like maybe you're asking for something else?

Feel free to give me a call you'd like to discuss.

Kenny

**Comment by karthikSenthi** [comment]
Hi Kenny,

To answer your questions,

- The 0.025mm for kerf width is a general guidance. The laser kerf width can be more than that depending on your final dimensions that you are trying to achieve. You can calculate the required kerf width based on Eqn 3.38 since you know your w_strut_raw ( w_strut_raw= targeted_finished_w_strut+m_width). If you are fine with a higher finished w_strut then you can assume both the w_kerf and m_width to be 0.025mm.

-  The as cut configuration should be independent of the "m_width" as "m_width" corresponds to the material removal that you expect from surface processing.

Karthik

**Comment by kenaycock** [comment]
Hi Karthik,

"If you are fine with a higher finished w_strut then you can assume both
the w_kerf and m_width to be 0.025mm."

Ah, I see. My aim was to make the struts as wide as possible, so
w_kerf=m_width=0.025mm is fine.

With this information, is the DXF file suitable as-is? I will correct the
"m_width" value tonight.

Kenny

**Comment by karthikSenthi** [comment]
If that's the case the DXF should be good.

**Comment by kenaycock** [comment]
Okay, thanks, Karthik. Sorry for the mixup. I didn't realize that you would
be treating the "finished" drawings as target dimensions, but that makes
sense.

Now that I think about it some more, it probably would not be a bad idea to
make the gap between the struts a *little* wider to make sure we do not
have too much strut-strut interference during sheathing, etc.

What is the range of kerf width that you can achieve with the laser in a
single pass? Would 0.050mm be acceptable?

**Comment by karthikSenthi** [comment]
Sure it can be more than 0.025mm for the kerf_width and we can do a multi-pass cut to get to 0.050 mm kerf width. If it is wider, it will be easier and more uniform for the laser cutting to get the targeted kerf_width at the laser entry and exit point.

**Comment by kenaycock** [comment]
I uploaded new files with:
* w_kerf = 0.050mm
* m_width = 0.025mm

This gives us a total gap between struts of 0.075mm in the "finished" configuration, which is close to what we had in the "Rev1" CAD model that I analyzed with FEA (0.1mm).

Can you take a look at the files one more time? I think we are close now.

**Comment by karthikSenthi** [comment]
Hi Kenny,

It looks all good now. Nice job.

Thanks,
Karthik
